<?php

use Crispcode\LaravelInfluxDB\InfluxServiceProvider;

class TestCase extends \Orchestra\Testbench\TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function getPackageProviders($app)
    {
        return [
            InfluxServiceProvider::class,
        ];
    }

    protected function getEnvironmentSetUp($app)
    {

    }
}